# -*- coding: utf-8 -*-
"""AI BASESD ASSESSMENT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F_IAmok1d23Fb0lLlGKYd-jKjT50HDSu
"""

# Install necessary libraries
# !pip install --upgrade gradio transformers rake-nltk pymupdf nltk wikipedia-api networkx matplotlib spacy pillow tqdm deep-translator pdfminer.six reportlab pdf2image pytesseract --quiet
# !python -m spacy download en_core_web_sm -q
# !apt-get update -q
# !apt-get install -y poppler-utils tesseract-ocr -q

# Import libraries
import gradio as gr
import fitz
from transformers import pipeline
from rake_nltk import Rake
import random
import nltk
import spacy
import wikipediaapi
import networkx as nx
import matplotlib.pyplot as plt
from PIL import Image
import io
from deep_translator import GoogleTranslator
from pdfminer.high_level import extract_text
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
import requests
import os
from pdf2image import convert_from_path
import pytesseract
import tempfile
import logging
from concurrent.futures import ThreadPoolExecutor
from tqdm import tqdm
from collections import defaultdict
import re
import warnings
import time

warnings.filterwarnings("ignore", category=FutureWarning)

# Configure logging to suppress warnings and below
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# Download NLTK resources
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')

# Load models
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import torch

class CustomSummarizer:
    def __init__(self):
        self.tokenizer = AutoTokenizer.from_pretrained("facebook/bart-large-cnn")
        self.model = AutoModelForSeq2SeqLM.from_pretrained("facebook/bart-large-cnn")
        self.device = "cuda" if torch.cuda.is_available() else ("mps" if torch.backends.mps.is_available() else "cpu")
        self.model.to(self.device)
    
    def __call__(self, text, max_length=130, min_length=30, do_sample=False):
        inputs = self.tokenizer([text], max_length=1024, return_tensors="pt", truncation=True).to(self.device)
        summary_ids = self.model.generate(
            inputs["input_ids"], 
            max_length=max_length, 
            min_length=min_length, 
            do_sample=do_sample
        )
        summary_text = self.tokenizer.batch_decode(summary_ids, skip_special_tokens=True)[0]
        return [{'summary_text': summary_text}]

summarizer = CustomSummarizer()
rake = Rake()
nlp = spacy.load("en_core_web_sm")
wiki = wikipediaapi.Wikipedia(user_agent='CombinedApp/1.0', language='en')

# Font setup for translation with updated URLs
font_configs = {
    "Latin": ("https://github.com/googlefonts/noto-fonts/raw/main/hinted/ttf/NotoSans/NotoSans-Regular.ttf", "NotoSans-Regular.ttf", "NotoSans"),
    "Chinese": ("https://github.com/googlefonts/noto-cjk/raw/main/Sans/Variable/TTF/Subset/NotoSansCJKsc-VF.ttf", "NotoSansCJKsc-VF.ttf", "NotoSansSC"),
    "Arabic": ("https://github.com/googlefonts/noto-fonts/raw/main/hinted/ttf/NotoSansArabic/NotoSansArabic-Regular.ttf", "NotoSansArabic-Regular.ttf", "NotoSansArabic"),
    "Devanagari": ("https://github.com/googlefonts/noto-fonts/raw/main/hinted/ttf/NotoSansDevanagari/NotoSansDevanagari-Regular.ttf", "NotoSansDevanagari-Regular.ttf", "NotoSansDevanagari"),
    "Tamil": ("https://github.com/googlefonts/noto-fonts/raw/main/hinted/ttf/NotoSansTamil/NotoSansTamil-Regular.ttf", "NotoSansTamil-Regular.ttf", "NotoSansTamil"),
    "Telugu": ("https://github.com/googlefonts/noto-fonts/raw/main/hinted/ttf/NotoSansTelugu/NotoSansTelugu-Regular.ttf", "NotoSansTelugu-Regular.ttf", "NotoSansTelugu"),
    "Japanese": ("https://github.com/googlefonts/noto-cjk/raw/main/Sans/Variable/TTF/Subset/NotoSansCJKjp-VF.ttf", "NotoSansCJKjp-VF.ttf", "NotoSansJP"),
    "Korean": ("https://github.com/googlefonts/noto-cjk/raw/main/Sans/Variable/TTF/Subset/NotoSansCJKkr-VF.ttf", "NotoSansCJKkr-VF.ttf", "NotoSansKR"),
    "Cyrillic": ("https://github.com/googlefonts/noto-fonts/raw/main/hinted/ttf/NotoSans/NotoSans-Regular.ttf", "NotoSans-Regular.ttf", "NotoSans"),
    "Thai": ("https://github.com/googlefonts/noto-fonts/raw/main/hinted/ttf/NotoSansThai/NotoSansThai-Regular.ttf", "NotoSansThai-Regular.ttf", "NotoSansThai"),
    "Bengali": ("https://github.com/googlefonts/noto-fonts/raw/main/hinted/ttf/NotoSansBengali/NotoSansBengali-Regular.ttf", "NotoSansBengali-Regular.ttf", "NotoSansBengali"),
}

for script, (url, filename, font_name) in font_configs.items():
    if not os.path.exists(filename):
        try:
            logging.info(f"Downloading font {filename} from {url}")
            response = requests.get(url, timeout=10)
            response.raise_for_status()
            with open(filename, "wb") as f:
                f.write(response.content)
            logging.info(f"Successfully downloaded {filename}")
        except requests.RequestException as e:
            logging.error(f"Failed to download {filename}: {e}")
            continue

    if os.path.exists(filename):
        try:
            pdfmetrics.registerFont(TTFont(font_name, filename))
            logging.info(f"Registered font: {font_name}")
        except Exception as e:
            logging.error(f"Failed to register {font_name}: {e}")
    else:
        logging.warning(f"Font file {filename} not found; skipping registration.")

language_to_script = {
    "arabic": "Arabic", "chinese (simplified)": "Chinese", "chinese (traditional)": "Chinese",
    "hindi": "Devanagari", "tamil": "Tamil", "telugu": "Telugu", "japanese": "Japanese",
    "korean": "Korean", "russian": "Cyrillic", "thai": "Thai", "bengali": "Bengali",
    "french": "Latin", "spanish": "Latin", "english": "Latin", "german": "Latin",
    "italian": "Latin", "portuguese": "Latin",
}

# Helper function to count verbs in a sentence
def count_verbs(sentence):
    doc = nlp(sentence)
    return sum(1 for token in doc if token.pos_ == "VERB")

# MCQ Generation Functions
def read_pdf(file_path):
    text = ""
    with fitz.open(file_path) as pdf_document:
        for page_num in range(pdf_document.page_count):
            page = pdf_document.load_page(page_num)
            text += page.get_text("text")
    paragraphs = [para.strip() for para in text.split('\n\n') if para.strip()]
    return paragraphs if paragraphs else ["No readable text found in the PDF."]

def truncate_text(context, max_tokens=512):
    words = context.split()
    if len(words) > max_tokens:
        return ' '.join(words[:max_tokens])
    return context

def get_summary(paragraphs):
    combined_text = " ".join(paragraphs)
    truncated_context = truncate_text(combined_text)
    input_length = len(truncated_context.split())
    max_length = max(5, input_length // 2)
    min_length = max(3, max_length // 2)
    summarized_text = summarizer(truncated_context, max_length=max_length, min_length=min_length, do_sample=False)
    return summarized_text[0]['summary_text']

def get_keywords(summary_text):
    rake.extract_keywords_from_text(summary_text)
    keywords = rake.get_ranked_phrases()[:50]
    if len(keywords) < 10:
        doc = nlp(summary_text)
        additional_keywords = [
            token.text for token in doc
            if token.pos_ in ["NOUN", "ADJ", "VERB"] and len(token.text) > 2
            and token.text.lower() not in [kw.lower() for kw in keywords]
        ]
        keywords.extend(additional_keywords[:max(0, 10 - len(keywords))])
    keywords = [re.sub(r'[^a-zA-Z0-9\s]', '', kw).strip() for kw in keywords]
    return [kw for kw in keywords if kw and len(kw) > 2]

def detect_content_theme(keywords):
    motivational_indicators = {"inspire", "motivation", "goal", "success", "achieve", "resilience", "encourage", "aspire", "drive", "passion"}
    leadership_indicators = {"leader", "leadership", "team", "decision", "vision", "manage", "strategy", "guide", "direct", "influence"}

    keyword_set = set(word.lower() for kw in keywords for word in kw.split())
    motivational_score = len(keyword_set & motivational_indicators)
    leadership_score = len(keyword_set & leadership_indicators)

    if motivational_score > leadership_score and motivational_score > 0:
        return "motivational"
    elif leadership_score > 0:
        return "leadership"
    return "computing"

def get_multiple_choice_options(correct_answer, summary_text, used_options, theme):
    # Default context if summary_text is uninformative
    if "No readable text" in summary_text:
        if theme == "motivational":
            summary_text = "The team finds motivation through inspiring leadership and a shared vision for success."
        elif theme == "leadership":
            summary_text = "The leader guides the team with a clear strategy and effective decision-making."
        else:
            summary_text = "A computer system includes various components like processor, memory, storage, and input/output devices."
        logging.info(f"Using default summary text for {theme} theme due to uninformative input.")

    # Clean the correct answer
    correct_answer = re.sub(r'[^a-zA-Z0-9\s]', '', correct_answer).strip()
    if not correct_answer:
        raise ValueError("Correct answer is empty after cleaning.")

    doc = nlp(summary_text)
    potential_distractors = [token.text for token in doc if token.pos_ in ["NOUN", "ADJ", "VERB"] and len(token.text) > 2]
    potential_distractors = [re.sub(r'[^a-zA-Z0-9\s]', '', d).strip() for d in potential_distractors if d]
    distractors = [opt for opt in potential_distractors if opt.lower() != correct_answer.lower() and opt.lower() not in [uo.lower() for uo in used_options] and len(opt) > 1]
    logging.debug(f"Potential distractors from summary: {potential_distractors}")
    logging.debug(f"Filtered distractors: {distractors}")

    # Define fallback distractors based on theme
    fallback_distractors = {
        "computing": [
            "processor", "memory", "storage", "input device", "output device", "network adapter",
            "graphics card", "software", "algorithm", "data structure", "interface", "protocol",
            "database", "server", "client", "cloud", "security", "encryption", "user profile",
            "application", "system update", "hardware", "firmware", "cache", "virtual memory",
            "operating system", "driver", "module", "component", "sensor", "controller",
            "bandwidth", "latency", "throughput", "compatibility", "configuration"
        ],
        "motivational": [
            "inspiration", "motivation", "goal", "success", "resilience", "encouragement", "aspiration",
            "drive", "passion", "determination", "effort", "commitment", "vision", "hope", "optimism",
            "achievement", "progress", "support", "confidence", "focus", "dedication", "team spirit",
            "ambition", "perseverance", "energy", "enthusiasm", "belief", "empowerment", "growth",
            "self-improvement", "challenge", "reward", "fulfillment", "purpose"
        ],
        "leadership": [
            "leader", "leadership", "team", "decision", "vision", "strategy", "management", "guidance",
            "direction", "influence", "communication", "collaboration", "responsibility", "authority",
            "planning", "execution", "motivation", "delegation", "support", "trust", "innovation",
            "problem-solving", "adaptability", "empowerment", "coaching", "mentoring", "organization",
            "inspiration", "accountability", "ethics", "culture", "productivity", "goals"
        ]
    }

    # Add fallback distractors if needed
    theme_distractors = fallback_distractors.get(theme, fallback_distractors["computing"])
    if len(distractors) < 3:
        additional_distractors = [d for d in theme_distractors if d.lower() != correct_answer.lower() and d.lower() not in [uo.lower() for uo in used_options]]
        distractors.extend(additional_distractors[:max(0, 3 - len(distractors))])
        logging.debug(f"After adding {theme} fallback distractors: {distractors}")

    # Dynamic generic distractors as final fallback
    if len(distractors) < 3:
        if theme == "motivational":
            generic_base = ["motivational factor", "inspirational element", "success principle"]
        elif theme == "leadership":
            generic_base = ["leadership quality", "team strategy", "management tactic"]
        else:
            generic_base = ["generic component", "system part", "hardware unit"]
        current_count = 1
        while len(distractors) < 3:
            for base in generic_base:
                if len(distractors) >= 3:
                    break
                generic_option = f"{base} {current_count}"
                if generic_option.lower() != correct_answer.lower() and generic_option.lower() not in [uo.lower() for uo in used_options]:
                    distractors.append(generic_option)
                    logging.debug(f"Added generic distractor: {generic_option}")
                current_count += 1

    # Ensure exactly 3 distractors
    distractors = distractors[:3]
    options = distractors
    random.shuffle(options)
    options.append(correct_answer)
    random.shuffle(options)

    # Final validation
    if len(options) != 4 or not all(options):
        logging.error(f"Failed to generate 4 options for correct_answer '{correct_answer}'. Got {len(options)} options: {options}")
        raise ValueError(f"Unable to generate 4 unique options for '{correct_answer}'. Only {len(options)} options available.")

    logging.debug(f"Final options for '{correct_answer}': {options}")
    return options

def generate_mcqs(file_path, topic, num_mcqs, blooms_level):
    logging.info(f"Starting generate_mcqs with num_mcqs={num_mcqs}, topic='{topic}', blooms_level='{blooms_level}'")

    # Define question templates for each theme and Bloom's level
    question_templates = {
        "computing": {
            "remembering": [
                "According to the text, what is '{keyword}' in the context of the system?",
                "In the described system, who is associated with '{keyword}'?",
                "Where does the text say '{keyword}' is typically found in the system?",
                "Based on the summary, when did '{keyword}' become significant?",
                "As per the text, how is '{keyword}' defined in the system?",
                "What are the main characteristics of '{keyword}' according to the text?",
                "Can you define '{keyword}' based on the system's description?",
                "What does '{keyword}' mean in the system as per the summary?",
                "How would you identify '{keyword}' in the system described?",
                "What does the text say about '{keyword}' in the system?"
            ],
            "understanding": [
                "How does the text explain the role of '{keyword}' in the system?",
                "What is the main idea behind '{keyword}' in the system's context?",
                "According to the summary, what are the key ideas related to '{keyword}'?",
                "How does the text compare '{keyword}' to other components?",
                "What is the difference between '{keyword}' and other parts as per the text?",
                "How would you classify '{keyword}' in the system described?",
                "What can you infer from the use of '{keyword}' in the text?",
                "What are the main points about '{keyword}' in the system's context?",
                "How would you rephrase the purpose of '{keyword}' based on the text?"
            ],
            "applying": [
                "In the system described, how would you use '{keyword}'?",
                "What would happen if you applied '{keyword}' to the system in the text?",
                "How would you demonstrate the function of '{keyword}' in this system?",
                "How would you apply '{keyword}' in a task within the system?",
                "What would you do to implement '{keyword}' in the described system?",
                "How would you solve a problem in the system using '{keyword}'?",
                "How would you adapt '{keyword}' for a specific use in the system?",
                "How would you modify '{keyword}' to improve the system's performance?",
                "How would you illustrate the use of '{keyword}' in the system?"
            ],
            "analyzing": [
                "What is the relationship between '{keyword}' and the system's performance?",
                "How can you distinguish '{keyword}' from other components in the text?",
                "What are the advantages of using '{keyword}' in the system described?",
                "According to the text, what are the disadvantages of '{keyword}'?",
                "What causes '{keyword}' to be effective in the system?",
                "What is the effect of '{keyword}' on the system's operations?",
                "How would you categorize '{keyword}' among other system parts?",
                "What patterns can you identify in the use of '{keyword}' in the text?",
                "How does '{keyword}' compare to other components in the system?"
            ],
        },
        "motivational": {
            "remembering": [
                "According to the text, what is '{keyword}' in the context of motivation?",
                "Who is associated with '{keyword}' in the motivational story?",
                "Where does the text say '{keyword}' is most impactful for motivation?",
                "Based on the summary, when did '{keyword}' inspire the team?",
                "As per the text, how is '{keyword}' defined in terms of motivation?",
                "What are the main characteristics of '{keyword}' in the motivational context?",
                "Can you define '{keyword}' based on the motivational theme?",
                "What does '{keyword}' mean for motivation as per the summary?",
                "How would you identify '{keyword}' in the motivational narrative?",
                "What does the text say about '{keyword}' in the context of motivation?"
            ],
            "understanding": [
                "How does the text explain the role of '{keyword}' in motivating the team?",
                "What is the main idea behind '{keyword}' in the motivational context?",
                "According to the summary, what are the key ideas related to '{keyword}' in motivation?",
                "How does the text compare '{keyword}' to other motivational factors?",
                "What is the difference between '{keyword}' and other motivational elements?",
                "How would you classify '{keyword}' in the motivational narrative?",
                "What can you infer from the use of '{keyword}' in the motivational text?",
                "What are the main points about '{keyword}' in the context of motivation?",
                "How would you rephrase the purpose of '{keyword}' in motivating others?"
            ],
            "applying": [
                "In the motivational context described, how would you use '{keyword}'?",
                "What would happen if you applied '{keyword}' to inspire a team?",
                "How would you demonstrate the effect of '{keyword}' in a motivational setting?",
                "How would you apply '{keyword}' to encourage someone based on the text?",
                "What would you do to implement '{keyword}' in a motivational scenario?",
                "How would you solve a lack of motivation using '{keyword}'?",
                "How would you adapt '{keyword}' for a specific motivational goal?",
                "How would you modify '{keyword}' to enhance motivation in the team?",
                "How would you illustrate the use of '{keyword}' in a motivational context?"
            ],
            "analyzing": [
                "What is the relationship between '{keyword}' and team motivation in the text?",
                "How can you distinguish '{keyword}' from other motivational factors?",
                "What are the advantages of using '{keyword}' for motivation as per the text?",
                "According to the text, what are the challenges of '{keyword}' in motivation?",
                "What causes '{keyword}' to be effective in motivating others?",
                "What is the effect of '{keyword}' on the team's motivation?",
                "How would you categorize '{keyword}' among other motivational elements?",
                "What patterns can you identify in the use of '{keyword}' for motivation?",
                "How does '{keyword}' compare to other motivational strategies in the text?"
            ],
        },
        "leadership": {
            "remembering": [
                "According to the text, what is '{keyword}' in the context of leadership?",
                "Who is associated with '{keyword}' in the leadership narrative?",
                "Where does the text say '{keyword}' is most effective in leadership?",
                "Based on the summary, when did '{keyword}' impact the team's leadership?",
                "As per the text, how is '{keyword}' defined in terms of leadership?",
                "What are the main characteristics of '{keyword}' in the leadership context?",
                "Can you define '{keyword}' based on the leadership theme?",
                "What does '{keyword}' mean for leadership as per the summary?",
                "How would you identify '{keyword}' in the leadership scenario?",
                "What does the text say about '{keyword}' in the context of leadership?"
            ],
            "understanding": [
                "How does the text explain the role of '{keyword}' in effective leadership?",
                "What is the main idea behind '{keyword}' in the leadership context?",
                "According to the summary, what are the key ideas related to '{keyword}' in leadership?",
                "How does the text compare '{keyword}' to other leadership qualities?",
                "What is the difference between '{keyword}' and other leadership traits?",
                "How would you classify '{keyword}' in the leadership narrative?",
                "What can you infer from the use of '{keyword}' in the leadership text?",
                "What are the main points about '{keyword}' in the context of leadership?",
                "How would you rephrase the purpose of '{keyword}' in leading a team?"
            ],
            "applying": [
                "In the leadership scenario described, how would you use '{keyword}'?",
                "What would happen if you applied '{keyword}' to lead a team?",
                "How would you demonstrate the effect of '{keyword}' in a leadership role?",
                "How would you apply '{keyword}' to manage a team based on the text?",
                "What would you do to implement '{keyword}' in a leadership scenario?",
                "How would you solve a leadership challenge using '{keyword}'?",
                "How would you adapt '{keyword}' for a specific leadership goal?",
                "How would you modify '{keyword}' to improve leadership effectiveness?",
                "How would you illustrate the use of '{keyword}' in a leadership context?"
            ],
            "analyzing": [
                "What is the relationship between '{keyword}' and effective leadership in the text?",
                "How can you distinguish '{keyword}' from other leadership qualities?",
                "What are the advantages of using '{keyword}' in leadership as per the text?",
                "According to the text, what are the challenges of '{keyword}' in leadership?",
                "What causes '{keyword}' to be effective in leading a team?",
                "What is the effect of '{keyword}' on the team's performance under leadership?",
                "How would you categorize '{keyword}' among other leadership traits?",
                "What patterns can you identify in the use of '{keyword}' in leadership?",
                "How does '{keyword}' compare to other leadership strategies in the text?"
            ],
        }
    }

    paragraphs = read_pdf(file_path)
    if topic.strip():
        filtered_paragraphs = [para for para in paragraphs if topic.lower() in para.lower()]
    else:
        filtered_paragraphs = paragraphs
    if not filtered_paragraphs:
        return "No relevant content found."

    blooms_level = blooms_level.lower()
    if blooms_level not in ["remembering", "understanding", "applying", "analyzing"]:
        return f"Invalid Bloom's Taxonomy level: {blooms_level}. Choose from: Remembering, Understanding, Applying, Analyzing."

    mcq_count = 0
    output = []
    used_keywords = set()
    used_templates = []
    used_options = set()
    all_keywords = []

    # Collect all keywords and summary for theme detection
    for paragraph in filtered_paragraphs:
        summary_text = get_summary([paragraph])
        keywords = get_keywords(summary_text)
        all_keywords.extend(keywords)

    # Remove duplicates while preserving order
    all_keywords = list(dict.fromkeys([kw for kw in all_keywords if kw not in used_keywords]))
    logging.info(f"Extracted {len(all_keywords)} unique keywords from content: {all_keywords[:10]}...")

    # Detect the theme based on keywords
    theme = detect_content_theme(all_keywords)
    logging.info(f"Detected content theme: {theme}")

    # Select the appropriate question templates based on theme
    theme_templates = question_templates.get(theme, question_templates["computing"])
    available_templates = theme_templates[blooms_level]

    keyword_index = 0
    summary_text = get_summary(filtered_paragraphs)

    # Generate questions using the selected theme and Bloom's level
    while mcq_count < num_mcqs and keyword_index < len(all_keywords):
        keyword = all_keywords[keyword_index]
        if keyword in used_keywords:
            logging.debug(f"Skipping already used keyword: {keyword}")
            keyword_index += 1
            continue

        template_counts = {tpl: used_templates.count(tpl) for tpl in available_templates}
        min_count = min(template_counts.values()) if template_counts else 0
        preferred_templates = [tpl for tpl, count in template_counts.items() if count == min_count]
        question_template = random.choice(preferred_templates)
        used_templates.append(question_template)

        question = question_template.format(keyword=keyword)
        try:
            options = get_multiple_choice_options(keyword, summary_text, used_options, theme)
        except ValueError as e:
            logging.error(f"Failed to generate options for keyword '{keyword}': {str(e)}")
            keyword_index += 1
            continue

        question_block = (
            f"Question {mcq_count + 1}:\n"
            f"{question}\n"
            f"\n"
            f"Options:\n"
            f"A. {options[0].capitalize()}\n"
            f"B. {options[1].capitalize()}\n"
            f"C. {options[2].capitalize()}\n"
            f"D. {options[3].capitalize()}\n"
            f"\n"
        )
        output.append(question_block)
        mcq_count += 1
        used_keywords.add(keyword)
        used_options.update(options)
        keyword_index += 1
        logging.info(f"Generated question {mcq_count}/{num_mcqs} with keyword '{keyword}'")

    # Fallback loop: Generate remaining questions using fallback keywords
    if mcq_count < num_mcqs:
        remaining = num_mcqs - mcq_count
        fallback_keywords_base = {
            "computing": [
                "central processor", "memory module", "storage drive", "input mechanism", "output display",
                "network interface", "graphics processor", "system memory", "data controller", "power unit",
                "computing core", "data processor", "memory bank", "system board", "interface module",
                "control chip", "storage unit", "display adapter", "audio processor", "network card"
            ],
            "motivational": [
                "team inspiration", "shared goal", "success story", "motivational speech", "resilient effort",
                "encouraging vision", "aspirational drive", "passionate commitment", "dedicated focus",
                "optimistic outlook", "achievement milestone", "progress marker", "supportive culture",
                "confident approach", "determined mindset", "team spirit boost", "ambitious target",
                "perseverance lesson", "energetic push", "enthusiastic support"
            ],
            "leadership": [
                "team leader", "strategic vision", "decision maker", "guiding principle", "management style",
                "directional focus", "influential role", "communication skill", "collaborative effort",
                "responsible leader", "authoritative decision", "planned approach", "executive action",
                "motivational strategy", "delegation task", "supportive guidance", "trust building",
                "innovative solution", "problem solver", "adaptive leadership"
            ]
        }

        # Dynamically extend fallback keywords if needed
        theme_fallbacks = fallback_keywords_base.get(theme, fallback_keywords_base["computing"])
        fallback_keywords = []
        keyword_counter = 1
        while len(fallback_keywords) < remaining:
            for base in theme_fallbacks:
                if len(fallback_keywords) >= remaining:
                    break
                keyword = base if keyword_counter == 1 else f"{base} {keyword_counter}"
                if keyword not in used_keywords:
                    fallback_keywords.append(keyword)
            keyword_counter += 1

        # Reset used_options to allow more distractors in fallback mode
        used_options.clear()
        logging.info("Cleared used_options to allow more distractors in fallback.")

        for keyword in fallback_keywords:
            if mcq_count >= num_mcqs:
                break

            template_counts = {tpl: used_templates.count(tpl) for tpl in available_templates}
            min_count = min(template_counts.values())
            preferred_templates = [tpl for tpl, count in template_counts.items() if count == min_count]
            question_template = random.choice(preferred_templates)
            used_templates.append(question_template)

            question = question_template.format(keyword=keyword)
            try:
                options = get_multiple_choice_options(keyword, summary_text, used_options, theme)
            except ValueError as e:
                logging.error(f"Fallback failed for keyword '{keyword}': {str(e)}")
                # Retry with a modified keyword
                keyword_counter += 1
                keyword = f"generic term {keyword_counter}"
                logging.info(f"Retrying with modified keyword: {keyword}")
                try:
                    options = get_multiple_choice_options(keyword, summary_text, used_options, theme)
                except ValueError as e:
                    logging.error(f"Retry failed for modified keyword '{keyword}': {str(e)}")
                    continue

            question_block = (
                f"Question {mcq_count + 1}:\n"
                f"{question}\n"
                f"\n"
                f"Options:\n"
                f"A. {options[0].capitalize()}\n"
                f"B. {options[1].capitalize()}\n"
                f"C. {options[2].capitalize()}\n"
                f"D. {options[3].capitalize()}\n"
                f"\n"
            )
            output.append(question_block)
            mcq_count += 1
            used_keywords.add(keyword)
            used_options.update(options)
            logging.info(f"Generated fallback question {mcq_count}/{num_mcqs} with keyword '{keyword}'")

    if mcq_count < num_mcqs:
        remaining = num_mcqs - mcq_count
        output.append(f"Note: Only {mcq_count} questions could be generated due to limited content or option constraints. {remaining} more were requested.\n")

    logging.info(f"Completed generate_mcqs: Generated {mcq_count}/{num_mcqs} questions")
    return "".join(output) if output else "No MCQs generated."

# Knowledge Graph Functions (Unchanged)
def extract_text_from_pdf(pdf_file):
    try:
        with fitz.open(pdf_file) as doc:
            text = "".join(page.get_text("text") for page in doc)
        if not text.strip():
            logging.info("No text extracted directly; attempting OCR.")
            with tempfile.NamedTemporaryFile(suffix=".pdf", delete=False) as tmp_file:
                with fitz.open(pdf_file) as doc:
                    with open(tmp_file.name, 'wb') as f:
                        f.write(doc.write())
                images = convert_from_path(tmp_file.name, poppler_path='/usr/bin/')
                text = "\n".join(pytesseract.image_to_string(img, config='--psm 6') for img in images)
            os.remove(tmp_file.name)
        text = re.sub(r'\n\s*\n+', '\n', text)
        text = re.sub(r'[^\x00-\x7F]+', ' ', text)
        text = re.sub(r'\s+', ' ', text)
        text = re.sub(r'-\n', '', text)
        text = re.sub(r'\n', ' ', text)
        logging.debug(f"Extracted text (first 200 chars): {text[:200]}...")
        return text.strip() or "No text extracted from any page."
    except Exception as e:
        logging.error(f"PDF extraction failed: {str(e)}")
        return f"Error: {str(e)}"

def extract_entities(text):
    doc = nlp(text)
    entities = defaultdict(list)
    section_pattern = re.compile(r"^[IVXLC]+\.\s+[A-Za-z]+|^[0-9]+\.[0-9]*\s+[A-Za-z]+")
    for ent in doc.ents:
        if ent.label_ in ["PERSON", "ORG", "GPE", "LOC"] and not section_pattern.match(ent.text):
            entities[ent.text].append(ent.label_)
    merged_entities = {}
    entity_keys = sorted(entities.keys(), key=len, reverse=True)
    for ent in entity_keys:
        labels = entities[ent]
        matched = False
        for existing_ent in list(merged_entities.keys()):
            if ent.lower() in existing_ent.lower() or existing_ent.lower() in ent.lower():
                merged_entities[existing_ent]["labels"].extend(labels)
                matched = True
                break
        if not matched:
            merged_entities[ent] = {"labels": labels}
    unique_entities = {}
    for ent, data in merged_entities.items():
        label = max(set(data["labels"]), key=data["labels"].count, default="ENTITY")
        if label == "LOC" and any(keyword in ent.lower() for keyword in ["roadster", "quotes", "inspiration"]):
            label = "ENTITY"
        wiki_page = wiki.page(ent)
        wiki_id = None
        try:
            if wiki_page.summary:
                wiki_id = wiki_page.fullurl
        except (KeyError, AttributeError):
            wiki_id = None
        unique_entities[ent] = {"type": label, "wiki_id": wiki_id}
        logging.debug(f"Entity extracted: {ent} ({label})")
    logging.info(f"Extracted and linked {len(unique_entities)} entities")
    return unique_entities

def extract_relationships(text, entities):
    doc = nlp(text)
    relationships = set()
    verb_categories = {
        "born": "BORN_IN", "live": "LIVES_IN", "reside": "LIVES_IN", "grow": "GREW_UP_IN",
        "die": "DIED_IN", "marry": "MARRIED_TO", "work": "WORKS_AT", "employ": "EMPLOYED_BY",
        "found": "FOUNDED", "lead": "LEADS", "manage": "MANAGES", "join": "JOINED",
        "own": "OWNS", "create": "CREATED", "invent": "INVENTED", "attend": "ATTENDED",
        "study": "STUDIED_AT", "graduate": "GRADUATED_FROM", "teach": "TAUGHT_AT",
        "meet": "MET", "visit": "VISITED", "travel": "TRAVELED_TO", "speak": "SPOKE_AT",
        "collaborate": "COLLABORATED_WITH", "fight": "FOUGHT_WITH", "mention": "MENTIONED_WITH",
        "write": "WROTE", "publish": "PUBLISHED", "influence": "INFLUENCED", "inspire": "INSPIRED",
        "buy": "BOUGHT", "sell": "SOLD", "acquire": "ACQUIRED", "represent": "REPRESENTS",
        "participate": "PARTICIPATED_IN", "support": "SUPPORTED", "oppose": "OPPOSED",
        "discover": "DISCOVERED"
    }
    patterns = [
        (r"(?P<subj>[A-Za-z\s]+)\s+was\s+born\s+in\s+(?P<obj>[A-Za-z\s]+)", "BORN_IN"),
        (r"(?P<subj>[A-Za-z\s]+)\s+founded\s+(?P<obj>[A-Za-z\s]+)", "FOUNDED"),
        (r"(?P<subj>[A-Za-z\s]+)\s+works\s+(at|for)\s+(?P<obj>[A-Za-z\s]+)", "WORKS_AT"),
        (r"(?P<subj>[A-Za-z\s]+)\s+is\s+from\s+(?P<obj>[A-Za-z\s]+)", "FROM"),
        (r"(?P<subj>[A-Za-z\s]+)\s+created\s+(?P<obj>[A-Za-z\s]+)", "CREATED"),
    ]
    logging.info(f"Processing {len(list(doc.sents))} sentences for relationships")
    for pattern, rel_type in patterns:
        for match in re.finditer(pattern, text, re.IGNORECASE):
            subj = match.group("subj").strip()
            obj = match.group("obj").strip()
            subj_ent = next((e for e in entities.keys() if subj.lower() in e.lower() or e.lower() in subj.lower()), None)
            obj_ent = next((e for e in entities.keys() if obj.lower() in e.lower() or e.lower() in obj.lower()), None)
            if subj_ent and obj_ent and subj_ent != obj_ent:
                relationships.add((subj_ent, obj_ent, rel_type))
                logging.debug(f"Pattern-based relationship: {subj_ent} → {obj_ent} ({rel_type})")
    for sent in doc.sents:
        sent_entities = [e for e in entities.keys() if e.lower() in sent.text.lower()]
        if len(sent_entities) < 2:
            logging.debug(f"Skipping sentence with <2 entities: {sent.text[:50]}...")
            continue
        verb_found = False
        for token in sent:
            if token.pos_ == "VERB":
                subj = obj = prep_obj = None
                prep = None
                for child in token.children:
                    if child.dep_ in ["nsubj", "nsubjpass", "compound", "agent"]:
                        subj = child.text
                    elif child.dep_ in ["dobj", "attr", "pobj"]:
                        obj = child.text
                    elif child.dep_ == "prep":
                        prep = child.text
                        for grandkid in child.children:
                            if grandkid.dep_ in ["pobj"]:
                                prep_obj = grandkid.text
                subj_ent = next((e for e in sent_entities if subj and (subj.lower() in e.lower() or e.lower() in subj.lower())), None)
                obj_ent = next((e for e in sent_entities if (obj and (obj.lower() in e.lower() or e.lower() in obj.lower())) or
                               (prep_obj and (prep_obj.lower() in e.lower() or e.lower() in prep_obj.lower()))), None)
                if subj_ent and obj_ent and subj_ent != obj_ent:
                    verb = token.lemma_
                    rel = verb_categories.get(verb, None)
                    if not rel:
                        if prep:
                            if prep == "at" and entities.get(obj_ent, {}).get("type") in ["ORG", "GPE"]:
                                rel = "WORKS_AT" if verb in ["work", "serve", "speak"] else "EVENT_AT"
                            elif prep == "in" and entities.get(obj_ent, {}).get("type") in ["GPE", "LOC"]:
                                rel = "LIVES_IN" if verb in ["live", "reside", "stay"] else "EVENT_IN"
                            elif prep == "with":
                                rel = "COLLABORATED_WITH" if verb in ["work", "collaborate", "partner"] else "ASSOCIATED_WITH"
                            else:
                                rel = f"{verb.upper()}_{prep.upper()}"
                        else:
                            rel = f"{verb.upper()}_TO"
                    relationships.add((subj_ent, obj_ent, rel))
                    logging.debug(f"Dependency-based relationship: {subj_ent} → {obj_ent} ({rel})")
                    verb_found = True
        if not verb_found and len(sent_entities) >= 2:
            for i in range(len(sent_entities) - 1):
                e1, e2 = sent_entities[i], sent_entities[i + 1]
                if e1 != e2:
                    e1_type = entities.get(e1, {}).get("type")
                    e2_type = entities.get(e2, {}).get("type")
                    if e1_type == "PERSON" and e2_type in ["ORG", "GPE"]:
                        rel = "RELATED_TO"
                        relationships.add((e1, e2, rel))
                        logging.debug(f"Sentence co-occurrence relationship: {e1} → {e2} ({rel})")
    if not relationships:
        logging.info("No relationships found; inferring based on entity types.")
        entity_list = list(entities.items())
        for i, (ent1, attrs1) in enumerate(entity_list):
            for ent2, attrs2 in entity_list[i+1:]:
                if ent1 != ent2:
                    type1, type2 = attrs1["type"], attrs2["type"]
                    if type1 == "PERSON" and type2 == "ORG":
                        relationships.add((ent1, ent2, "FOUNDED"))
                        logging.debug(f"Inferred relationship: {ent1} --FOUNDED--> {ent2}")
                    elif type1 == "PERSON" and type2 == "GPE":
                        relationships.add((ent1, ent2, "BORN_IN"))
                        logging.debug(f"Inferred relationship: {ent1} --BORN_IN--> {ent2}")
                    elif type1 == "ORG" and type2 == "GPE":
                        relationships.add((ent1, ent2, "LOCATED_IN"))
                        logging.debug(f"Inferred relationship: {ent1} --LOCATED_IN--> {ent2}")
    G_temp = nx.DiGraph()
    for entity in entities.keys():
        G_temp.add_node(entity)
    for e1, e2, rel in relationships:
        G_temp.add_edge(e1, e2, relation=rel)
    isolated_nodes = list(nx.isolates(G_temp))
    if isolated_nodes:
        logging.info(f"Found {len(isolated_nodes)} isolated nodes: {isolated_nodes}")
        if G_temp.number_of_nodes() > len(isolated_nodes):
            non_isolated_nodes = [n for n in G_temp.nodes if n not in isolated_nodes]
            degree_dict = dict(G_temp.degree(non_isolated_nodes))
            central_node = max(degree_dict, key=degree_dict.get, default=non_isolated_nodes[0]) if degree_dict else non_isolated_nodes[0]
            if "Elon Musk" in G_temp.nodes:
                central_node = "Elon Musk"
            elif "Conclusion Elon Musk" in G_temp.nodes:
                central_node = "Conclusion Elon Musk"
            elif "Elon Musk Inspiration" in G_temp.nodes:
                central_node = "Elon Musk Inspiration"
            for node in isolated_nodes:
                node_type = entities.get(node, {}).get("type", "ENTITY")
                central_type = entities.get(central_node, {}).get("type", "ENTITY")
                if node_type == "PERSON" and central_type in ["ORG", "ENTITY"]:
                    rel = "ASSOCIATED_WITH"
                elif node_type == "ORG" and central_type == "PERSON":
                    rel = "FOUNDED_BY"
                elif node_type in ["GPE", "LOC"] and central_type == "PERSON":
                    rel = "VISITED"
                elif node_type == "ENTITY" and central_type == "PERSON":
                    rel = "CREATED_BY"
                else:
                    rel = "RELATED_TO"
                relationships.add((node, central_node, rel))
                logging.debug(f"Connected isolated node {node} to {central_node} with relation {rel}")
    if not relationships:
        logging.warning("No relationships extracted after all methods.")
    logging.info(f"Extracted {len(relationships)} unique relationships")
    return list(relationships)

def build_knowledge_graph(entities, relationships):
    G = nx.DiGraph()
    for entity, attrs in entities.items():
        G.add_node(entity, type=attrs["type"], wiki_id=attrs["wiki_id"])
    for e1, e2, rel in relationships:
        weight = 1.5 if rel != "RELATED_TO" else 0.8
        G.add_edge(e1, e2, relation=rel, weight=weight)
    logging.info(f"Built graph with {G.number_of_nodes()} nodes and {G.number_of_edges()} edges.")
    return G

def generate_graph_image(G):
    plt.figure(figsize=(16, 12))
    pos = nx.spring_layout(G, k=1.5, iterations=100, seed=42)
    node_degrees = dict(G.degree())
    max_degree = max(node_degrees.values(), default=1)
    node_sizes = [800 + 400 * (node_degrees[node] / max_degree) for node in G.nodes]
    node_colors = {"PERSON": "#a3cfbb", "ORG": "#80bdff", "GPE": "#ff9999", "LOC": "#ffcc99", "ENTITY": "#d9d9d9"}
    nx.draw_networkx_nodes(G, pos, node_color=[node_colors[G.nodes[n]["type"]] for n in G.nodes], node_size=node_sizes, alpha=0.9)
    nx.draw_networkx_edges(G, pos, edge_color="#6b7280", width=1.5, arrows=True, arrowstyle="-|>", arrowsize=15)
    nx.draw_networkx_labels(G, pos, font_size=10, font_weight="bold", verticalalignment="center", horizontalalignment="center")
    edge_labels = {(u, v): d["relation"] for u, v, d in G.edges(data=True)}
    nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels, font_size=8, label_pos=0.5, rotate=False)
    plt.tight_layout()
    plt.margins(0.1)
    buf = io.BytesIO()
    plt.savefig(buf, format="png", dpi=150, bbox_inches="tight")
    plt.close()
    buf.seek(0)
    return Image.open(buf)

def generate_questions(graph, num_questions, blooms_level):
    if not graph or graph.number_of_nodes() == 0:
        return "No entities or relationships in the graph to generate questions from."
    bloom_templates = {
        "remembering": {
            "PERSON": ["Who is {entity}?", "Where was {entity} born?", "When did {entity} start their career?"],
            "ORG": ["What is {entity}?", "Where is {entity} headquartered?", "When was {entity} founded?"],
            "GPE": ["Where is {entity} located?", "What is the capital of {entity}?", "When was {entity} established?"],
            "LOC": ["Where is {entity} situated?", "What is {entity} known for?", "When was {entity} discovered?"],
            "ENTITY": ["What is {entity}?", "Where is {entity} commonly found?", "When was {entity} introduced?"],
            "RELATION": ["Who did {source} collaborate with in {target}?", "What connects {source} to {target}?", "Where did {source} meet {target}?"]
        },
        "understanding": {
            "PERSON": ["What role does {entity} play?", "Why is {entity} influential?", "How is {entity} described in the text?"],
            "ORG": ["What is the mission of {entity}?", "How does {entity} operate?", "Why was {entity} established?"],
            "GPE": ["What is {entity} famous for?", "Why is {entity} culturally significant?", "How is {entity} governed?"],
            "LOC": ["What makes {entity} a notable location?", "Why is {entity} important?", "How is {entity} characterized?"],
            "ENTITY": ["What does {entity} represent in the context?", "Why is {entity} significant?", "How is {entity} defined?"],
            "RELATION": ["What is the relationship between {source} and {target}?", "Why are {source} and {target} connected?", "How do {source} and {target} interact?"]
        },
        "applying": {
            "PERSON": ["How might {entity} address a challenge?", "What could {entity} contribute to {target}?"],
            "ORG": ["How can {entity} be applied in a new project?", "What would happen if {entity} expands to {target}?"],
            "GPE": ["How could {entity} be used in a travel plan?", "What benefits does {entity} offer to {target}?"],
            "LOC": ["How might {entity} be utilized in modern times?", "What could {entity} provide to {target}?"],
            "ENTITY": ["How can {entity} be applied in a scenario?", "What role can {entity} play in {target}?"],
            "RELATION": ["How does the connection between {source} and {target} benefit a project?", "What can {source} offer to {target}?"]
        },
        "analyzing": {
            "PERSON": ["Why did {entity} influence {target}?", "How does {entity} compare to {target} in impact?"],
            "ORG": ["What factors contribute to {entity}'s success?", "How does {entity} differ from {target} in operations?"],
            "GPE": ["Why is {entity} distinct from {target}?", "What causes {entity}'s prominence?"],
            "LOC": ["How does {entity} relate to {target} geographically?", "Why is {entity} significant compared to {target}?"],
            "ENTITY": ["What makes {entity} different from {target}?", "How does {entity} impact {target}?"],
            "RELATION": ["Why are {source} and {target} linked in this way?", "How does the relationship between {source} and {target} affect outcomes?"]
        }
    }
    blooms_level = blooms_level.lower()
    if blooms_level not in bloom_templates:
        return f"Invalid Bloom's Taxonomy level: {blooms_level}. Choose from: Remembering, Understanding, Applying, Analyzing."
    possible_questions = []
    for entity, attrs in graph.nodes(data=True):
        entity_type = attrs.get("type", "ENTITY")
        templates = bloom_templates[blooms_level].get(entity_type, bloom_templates[blooms_level]["ENTITY"])
        for template in templates:
            try:
                question = template.format(
                    entity=entity,
                    target=random.choice(list(graph.nodes())) if "{target}" in template else ""
                )
                if count_verbs(question) == 1:
                    possible_questions.append(question)
            except (KeyError, ValueError) as e:
                logging.warning(f"Failed to format template for entity {entity}: {e}")
                continue
    for source, target, data in graph.edges(data=True):
        templates = bloom_templates[blooms_level]["RELATION"]
        for template in templates:
            try:
                question = template.format(source=source, target=target)
                if count_verbs(question) == 1:
                    possible_questions.append(question)
            except (KeyError, ValueError) as e:
                logging.warning(f"Failed to format relation template for {source} -> {target}: {e}")
                continue
    if not possible_questions:
        return "No questions could be generated from the graph."
    num_to_select = min(num_questions, len(possible_questions))
    if num_to_select < num_questions:
        logging.warning(f"Only {len(possible_questions)} unique questions available, requested {num_questions}.")
    selected_questions = random.sample(possible_questions, num_to_select)
    output = "\n".join([f"{i+1}. {q}" for i, q in enumerate(selected_questions)])
    if num_to_select < num_questions:
        output += f"\n\nNote: Only {num_to_select} unique questions could be generated due to limited graph content."
    return output

def process_knowledge_graph(pdf_file, num_questions, blooms_level):
    text = extract_text_from_pdf(pdf_file)
    entities = extract_entities(text)
    relationships = extract_relationships(text, entities)
    graph = build_knowledge_graph(entities, relationships)
    graph_img = generate_graph_image(graph) if graph.number_of_nodes() > 0 else None
    questions = generate_questions(graph, num_questions, blooms_level) if graph else "No questions generated."
    return graph_img, questions

# Translation Functions (Unchanged)
def get_font_for_language(target_language: str) -> str:
    script = language_to_script.get(target_language.lower(), "Latin")
    font_map = {
        "Latin": "NotoSans",
        "Chinese": "NotoSansSC",
        "Arabic": "NotoSansArabic",
        "Devanagari": "NotoSansDevanagari",
        "Tamil": "NotoSansTamil",
        "Telugu": "NotoSansTelugu",
        "Japanese": "NotoSansJP",
        "Korean": "NotoSansKR",
        "Cyrillic": "NotoSans",
        "Thai": "NotoSansThai",
        "Bengali": "NotoSansBengali",
    }
    font = font_map.get(script, "NotoSans")
    if font not in pdfmetrics.getRegisteredFontNames():
        logging.warning(f"Font {font} not available, falling back to NotoSans")
        return "NotoSans"
    return font

def extract_text_from_pdf_bytes(pdf_content: bytes) -> str:
    pdf_file = io.BytesIO(pdf_content)
    text = extract_text(pdf_file)
    if not text.strip():
        logging.warning("No text extracted with pdfminer, attempting OCR.")
        with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp_file:
            tmp_file.write(pdf_content)
            tmp_file.flush()
            images = convert_from_path(tmp_file.name, poppler_path='/usr/bin/')
            text = ""
            for img in images:
                text += pytesseract.image_to_string(img) + "\n\n"
            os.unlink(tmp_file.name)
        if not text.strip():
            return "No text extracted from the PDF. It might be image-based and OCR failed."
    logging.debug(f"Extracted text sample: {text[:100]}")
    return text

def filter_text_by_topic(text: str, topic: str) -> str:
    if not topic:
        return text
    paragraphs = text.split('\n\n')
    filtered_paragraphs = [p for p in paragraphs if topic.lower() in p.lower()]
    if not filtered_paragraphs:
        return "No content found for the specified topic."
    return '\n\n'.join(filtered_paragraphs)

def translate_text(text: str, target_language: str) -> str:
    translator = GoogleTranslator(source='en', target=target_language)
    max_chars = 5000
    translated_chunks = []
    sentences = nltk.sent_tokenize(text)
    current_chunk = ""
    for sentence in sentences:
        sentence = sentence.encode('utf-8', errors='replace').decode('utf-8')
        if len(current_chunk) + len(sentence) + 1 <= max_chars:
            current_chunk += sentence + " "
        else:
            try:
                translated_chunk = translator.translate(current_chunk.strip())
                if translated_chunk:
                    translated_chunks.append(translated_chunk)
                else:
                    translated_chunks.append(current_chunk.strip())
            except Exception as e:
                logging.error(f"Translation error: {e}")
                return f"Error translating to {target_language}: {e}"
            current_chunk = sentence + " "
    if current_chunk.strip():
        try:
            translated_chunk = translator.translate(current_chunk.strip())
            if translated_chunk:
                translated_chunks.append(translated_chunk)
            else:
                translated_chunks.append(current_chunk.strip())
        except Exception as e:
            logging.error(f"Final chunk translation error: {e}")
            return f"Error translating to {target_language}: {e}"
    translated_text = " ".join(translated_chunks)
    return translated_text

def create_pdf_and_preview(translated_text: str, target_language: str) -> tuple[str, str]:
    with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp_file:
        doc = SimpleDocTemplate(tmp_file.name, pagesize=letter)
        styles = getSampleStyleSheet()
        style = styles["Normal"]
        style.fontName = get_font_for_language(target_language)
        style.fontSize = 12
        style.leading = 14
        translated_text = translated_text.encode('utf-8', errors='replace').decode('utf-8')
        paragraphs = translated_text.split('\n\n')
        flowables = []
        for p in paragraphs:
            if p.strip():
                p = ''.join(c for c in p if ord(c) >= 32 or c in '\n\t')
                try:
                    flowables.append(Paragraph(p, style))
                except Exception as e:
                    logging.error(f"Paragraph rendering error: {e}")
                    flowables.append(Paragraph(f"[Rendering Error: {e}]", style))
        doc.build(flowables)
        pdf_path = tmp_file.name
    images = convert_from_path(pdf_path, first_page=1, last_page=1, poppler_path='/usr/bin/')
    preview_path = tempfile.mktemp(suffix=".png")
    images[0].save(preview_path, "PNG")
    return pdf_path, preview_path

def generate_wh_questions(translated_text: str, num_questions: int) -> str:
    sentences = nltk.sent_tokenize(translated_text)
    if not sentences:
        return "No sentences found to generate questions."
    doc = nlp(translated_text)
    all_sents = list(doc.sents)
    if not all_sents:
        return "No sentences parsed from the text."
    stopwords = {"like", "mean", "do", "is", "are", "be", "have"}
    question_strategies = [
        lambda sent: next((f"What role does {ent.text} play in the text?" for ent in sent.ents if ent.label_ == "PERSON" and count_verbs(ent.text) == 0), None),
        lambda sent: next((f"How is {ent.text} described in the context?" for ent in sent.ents if ent.label_ == "PERSON" and count_verbs(ent.text) == 0), None),
        lambda sent: next((f"Why is {ent.text} considered influential?" for ent in sent.ents if ent.label_ == "PERSON" and count_verbs(ent.text) == 0), None),
        lambda sent: next((f"What is {ent.text} known for?" for ent in sent.ents if ent.label_ in ["ORG", "GPE", "LOC"] and count_verbs(ent.text) == 0), None),
        lambda sent: next((f"Where is {ent.text} located according to the text?" for ent in sent.ents if ent.label_ in ["ORG", "GPE", "LOC"] and count_verbs(ent.text) == 0), None),
        lambda sent: (f"When did {sent.root.text} occur in the context?" if sent.root.pos_ == "VERB" and sent.root.text not in stopwords and count_verbs(sent.root.text) <= 1 else None),
        lambda sent: (f"What event caused {sent.root.text} to occur?" if sent.root.pos_ == "VERB" and sent.root.text not in stopwords and count_verbs(sent.root.text) <= 1 else None),
        lambda sent: next((f"What does {ent.text} represent in the document?" for ent in sent.ents if ent.label_ not in ["PERSON", "ORG", "GPE", "LOC"] and count_verbs(ent.text) == 0), None),
        lambda sent: next((f"Why is {ent.text} significant in the text?" for ent in sent.ents if count_verbs(ent.text) == 0), None),
        lambda sent: next((f"How does {ent.text} function according to the text?" for ent in sent.ents if ent.label_ == "ORG" and count_verbs(ent.text) == 0), None),
    ]
    all_questions = []
    used_sentences = set()
    for sent in all_sents:
        random.shuffle(question_strategies)
        for strategy in question_strategies:
            question = strategy(sent)
            if question and question.strip() not in all_questions:
                if count_verbs(question) == 1:
                    all_questions.append(question)
                    used_sentences.add(sent.text)
                    break
    if len(all_questions) < num_questions:
        for sent in all_sents:
            if len(all_questions) >= num_questions:
                break
            if sent.text in used_sentences:
                continue
            for strategy in question_strategies:
                question = strategy(sent)
                if question and question.strip() not in all_questions:
                    if count_verbs(question) == 1:
                        all_questions.append(question)
                        break
    if len(all_questions) < num_questions:
        remaining = num_questions - len(all_questions)
        entities = [ent.text for sent in all_sents for ent in sent.ents if count_verbs(ent.text) == 0]
        if entities:
            fallback_templates = [
                "What does {entity} represent in the text?",
                "Why is {entity} important in the context?",
                "How is {entity} described in the document?",
                "What is {entity} known for?",
                "When was {entity} mentioned in the text?"
            ]
            for i in range(remaining):
                if not entities:
                    break
                entity = random.choice(entities)
                template = random.choice(fallback_templates)
                question = template.format(entity=entity)
                if question not in all_questions and count_verbs(question) == 1:
                    all_questions.append(question)
    if len(all_questions) <= num_questions:
        selected_questions = all_questions
    else:
        step = max(1, len(all_questions) // num_questions)
        selected_questions = [all_questions[i] for i in range(0, len(all_questions), step)][:num_questions]
    if not selected_questions:
        return "Not enough content to generate questions."
    return "\n".join([f"{i+1}. {q}" for i, q in enumerate(selected_questions[:num_questions])])

def process_translation(pdf_file, target_language, topic, num_questions):
    if not pdf_file:
        return "Please upload a PDF file.", None, None, "No questions generated."
    pdf_content = pdf_file if isinstance(pdf_file, bytes) else pdf_file.read()
    target_language = target_language.lower()
    if target_language not in language_to_script:
        logging.info(f"Language {target_language} not explicitly mapped, using fallback font.")
    original_text = extract_text_from_pdf_bytes(pdf_content)
    if "No text extracted" in original_text:
        return original_text, None, None, "No questions generated."
    filtered_text = filter_text_by_topic(original_text, topic)
    if filtered_text == "No content found for the specified topic.":
        return filtered_text, None, None, "No questions generated."
    translated_text = translate_text(filtered_text, target_language)
    if "Error translating" in translated_text:
        return translated_text, None, None, "No questions generated."
    pdf_file_path, preview_path = create_pdf_and_preview(translated_text, target_language)
    questions = generate_wh_questions(translated_text, num_questions)
    return translated_text, pdf_file_path, preview_path, questions

# Combined Processing Function with Visibility Control and Status Output
def process_input(option, pdf_file, topic, num_questions, target_language, blooms_level):
    start_time = time.time()
    questions_output, graph_output, pdf_download, pdf_preview, text_output = None, None, None, None, None
    visibility = {"questions": False, "graph": False, "pdf": False, "text": False}
    logging.info(f"Processing input with option='{option}', num_questions={num_questions}")

    if option == "Generate MCQs from PDF":
        if not pdf_file:
            questions_output = "Please upload a PDF."
        else:
            with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp_file:
                try:
                    tmp_file.write(pdf_file)
                    tmp_file.flush()
                    questions_output = generate_mcqs(tmp_file.name, topic, num_questions, blooms_level)
                finally:
                    os.unlink(tmp_file.name)
        visibility["questions"] = True
    elif option == "Generate Knowledge Graph with Questions":
        if not pdf_file:
            questions_output = "Please upload a PDF."
        else:
            with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp_file:
                try:
                    tmp_file.write(pdf_file)
                    tmp_file.flush()
                    graph_img, questions = process_knowledge_graph(tmp_file.name, num_questions, blooms_level)
                    questions_output = questions
                    graph_output = graph_img
                finally:
                    os.unlink(tmp_file.name)
        visibility["questions"] = True
        visibility["graph"] = True
    elif option == "Translate PDF with Questions":
        if not pdf_file:
            questions_output = "Please upload a PDF."
        else:
            translated_text, pdf_path, preview_path, questions = process_translation(pdf_file, target_language, topic, num_questions)
            questions_output = questions
            pdf_download = pdf_path
            pdf_preview = preview_path
            text_output = translated_text
        visibility["questions"] = True
        visibility["pdf"] = True
        visibility["text"] = True
    else:
        questions_output = "Please select an option from the dropdown."
        visibility["questions"] = True

    end_time = time.time()
    runtime = end_time - start_time
    status_output = f"Processing Time: {runtime:.2f} seconds"
    return (
        gr.update(value=questions_output, visible=visibility["questions"]),
        gr.update(value=graph_output, visible=visibility["graph"]),
        gr.update(value=pdf_download, visible=visibility["pdf"]),
        gr.update(value=pdf_preview, visible=visibility["pdf"]),
        gr.update(value=text_output, visible=visibility["text"]),
        gr.update(value=status_output, visible=True)
    )

def process_with_status(option, pdf_file, topic, num_questions, target_language, blooms_level):
    yield (
        gr.update(visible=True),
        gr.update(visible=False),
        gr.update(visible=False),
        gr.update(visible=False),
        gr.update(visible=False),
        gr.update(value="Processing...", visible=True)
    )
    result = process_input(option, pdf_file, topic, num_questions, target_language, blooms_level)
    yield result

# Gradio Interface with Dynamic Visibility
translator = GoogleTranslator()
langs = translator.get_supported_languages(as_dict=True)
language_names = sorted(langs.keys())
with gr.Blocks(theme=gr.themes.Soft(primary_hue="blue"), title="AI BASED ASSESSMENT") as interface:
    gr.Markdown("<h1 style='text-align: center;'>AI BASED ASSESSMENT</h1>")
    gr.Markdown("<p style='text-align: center;'>Select an option below to begin.</p>")
    with gr.Row():
        with gr.Column(scale=1):
            option_input = gr.Dropdown(
                label="Processing Option",
                choices=[
                    "Generate MCQs from PDF",
                    "Generate Knowledge Graph with Questions",
                    "Translate PDF with Questions"
                ],
                value=None
            )
            pdf_input = gr.File(label="Upload PDF", file_types=[".pdf"], type="binary", visible=False)
            topic_input = gr.Textbox(label="Topic (optional)", placeholder="e.g., Machine Learning", visible=False)
            num_questions_input = gr.Slider(label="Number of Questions", minimum=1, maximum=30, step=1, value=5, visible=False)
            blooms_level_input = gr.Dropdown(
                label="Bloom's Taxonomy Level",
                choices=["Remembering", "Understanding", "Applying", "Analyzing"],
                value="Remembering",
                visible=False
            )
            lang_input = gr.Dropdown(label="Translation Language", choices=language_names, value="english", visible=False)
            submit_btn = gr.Button("Process", variant="primary", visible=False)
            status_output = gr.Textbox(label="Processing Status", visible=False)
        with gr.Column(scale=3):
            with gr.Tabs() as output_tabs:
                with gr.TabItem("Questions/MCQs", id="questions_tab") as questions_tab:
                    questions_output = gr.Textbox(label="Generated Questions/MCQs", lines=10, visible=False)
                with gr.TabItem("Knowledge Graph", id="graph_tab") as graph_tab:
                    graph_output = gr.Image(label="Knowledge Graph", height=400, visible=False)
                with gr.TabItem("Translated PDF", id="pdf_tab") as pdf_tab:
                    pdf_download = gr.File(label="Download Translated PDF", visible=False)
                    pdf_preview = gr.Image(label="PDF Preview", height=400, visible=False)
                with gr.TabItem("Translated Text", id="text_tab") as text_tab:
                    text_output = gr.Textbox(label="Translated Text", lines=10, visible=False)
    def update_inputs(option):
        if option is None:
            return (
                gr.update(visible=False),
                gr.update(visible=False),
                gr.update(visible=False),
                gr.update(visible=False),
                gr.update(visible=False),
                gr.update(visible=False)
            )
        pdf_visible = option in ["Generate MCQs from PDF", "Generate Knowledge Graph with Questions", "Translate PDF with Questions"]
        topic_visible = option in ["Generate MCQs from PDF", "Translate PDF with Questions"]
        num_questions_visible = option in ["Generate MCQs from PDF", "Generate Knowledge Graph with Questions", "Translate PDF with Questions"]
        blooms_visible = option in ["Generate MCQs from PDF", "Generate Knowledge Graph with Questions"]
        lang_visible = option == "Translate PDF with Questions"
        submit_visible = option is not None
        return (
            gr.update(visible=pdf_visible),
            gr.update(visible=topic_visible),
            gr.update(visible=num_questions_visible),
            gr.update(visible=blooms_visible),
            gr.update(visible=lang_visible),
            gr.update(visible=submit_visible)
        )
    option_input.change(
        fn=update_inputs,
        inputs=option_input,
        outputs=[pdf_input, topic_input, num_questions_input, blooms_level_input, lang_input, submit_btn]
    )
    submit_btn.click(
        fn=process_with_status,
        inputs=[option_input, pdf_input, topic_input, num_questions_input, lang_input, blooms_level_input],
        outputs=[questions_output, graph_output, pdf_download, pdf_preview, text_output, status_output]
    )
interface.launch()

